version: '3.8'
services:
  postgres-test:
    image: postgres:13
    environment:
      POSTGRES_USER: appctrl
      POSTGRES_PASSWORD: appctrl
      POSTGRES_DB: appctrl_test
    ports:
      - "5433:5432"

  backend-test:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres-test
    environment:
      NODE_ENV: test
      DATABASE_URL: postgres://appctrl:appctrl@postgres-test:5432/appctrl_test
    command: npm test

  bff-test:
    build:
      context: ./bff
      dockerfile: Dockerfile
    depends_on:
      - backend-test
    environment:
      NODE_ENV: test
    command: npm test

  web-test:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
    environment:
      NODE_ENV: test
      CI: "true"
    command: npm test

  mobile-test:
    build:
      context: ./frontend/mobile
      dockerfile: Dockerfile
    environment:
      NODE_ENV: test
      CI: "true"
    command: npm test

  tests:
    image: node:16
    depends_on:
      - backend-test
      - bff-test
      - web-test
      - mobile-test
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
        echo 'Waiting for services to complete tests...' &&
        exit 0
      "