version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./observability/prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./observability/grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo

  loki:
    image: grafana/loki:latest
    volumes:
      - ./observability/loki:/etc/loki
      - loki-data:/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml

  tempo:
    image: grafana/tempo:latest
    volumes:
      - ./observability/tempo:/etc/tempo
      - tempo-data:/tmp/tempo
    ports:
      - "3200:3200"
    command: -config.file=/etc/tempo/tempo-config.yml

volumes:
  prometheus-data:
  grafana-data:
  loki-data:
  tempo-data: