global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']
  - job_name: 'bff'
    static_configs:
      - targets: ['bff:4000']
  - job_name: 'web'
    static_configs:
      - targets: ['web:3001']